name: "CF-Pages Deploy Action"
description: "Customized Action for CF-Pages deployment"
branding:
  icon: "sunrise"
  color: "yellow"
inputs:
  apiToken:
    description: "Cloudflare API Token"
    required: true
  accountId:
    description: "Cloudflare Account ID"
    required: true
  projectName:
    description: "The name of the Pages project to upload to"
    required: true
  directory:
    description: "The directory of static assets to upload"
    required: true
  gitHubToken:
    description: "GitHub Token"
    required: false
  branch:
    description: "The name of the branch you want to deploy to"
    required: false
  workingDirectory:
    description: "The working directory in which to run Wrangler"
    required: false
  wranglerVersion:
    description: "The version of Wrangler to use"
    required: false
    default: "3"
  logsOnFailure:
    description: "Include logs from failed deployments in the deployment summary"
    required: false
    default: "false"
runs:
  using: "node20"
  main: "index.js"
